support flutter 3.27.0, processInitialRoute to run automatically
gree/patapata pull request #33
Opened 2024-12-20 04:59 UTC by matsuyani556

# Issue Number
fixes https://github.com/gree/patapata/issues/31
fixes https://github.com/gree/patapata/issues/32

# Summary
- Flutter 3.27.0 Support
- processInitialRoute to run automatically

2024-12-23 08:51 UTC, Moncader requested changes

2024-12-23 08:51 UTC, Moncader commented on packages/patapata_core/lib/src/widgets/standard_page.dart
> +    final tWithDymmySplashPage =
```suggestion
    final tWithDummySplashPage =
```

2025-01-07 00:49 UTC, ms11165 approved these changes

2025-01-07 02:06 UTC, Moncader approved these changes

2025-01-07 02:09 UTC, merged